// <auto-generated />
namespace TeduShop.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addFunctionIdentityUserBai15 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addFunctionIdentityUserBai15));
        
        string IMigrationMetadata.Id
        {
            get { return "201811011627465_add-Function-IdentityUser-Bai15"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
